// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxUnc1OfnvMLLPhFk8sJWsfxX--NSPPLo',
    appId: '1:1090528583428:android:cd157d8ab5aeb2b8aaba51',
    messagingSenderId: '1090528583428',
    projectId: 'fluttercrud-d6367',
    databaseURL: 'https://fluttercrud-d6367-default-rtdb.firebaseio.com',
    storageBucket: 'fluttercrud-d6367.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCz-JkiZs3b-eWnmQp0OpzRllm4mosr3rs',
    appId: '1:1090528583428:ios:bcfe4ef16c520db5aaba51',
    messagingSenderId: '1090528583428',
    projectId: 'fluttercrud-d6367',
    databaseURL: 'https://fluttercrud-d6367-default-rtdb.firebaseio.com',
    storageBucket: 'fluttercrud-d6367.appspot.com',
    androidClientId: '1090528583428-02jbp3b6b03anrv9kjuuvetvoecql2i1.apps.googleusercontent.com',
    iosClientId: '1090528583428-d4umpkn1pg1sjn452pe0ktcc062cp65h.apps.googleusercontent.com',
    iosBundleId: 'com.example.recipeChecked',
  );
}
